// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLayoutPreset(arg1, arg2) {
  return window['go']['main']['App']['ApplyLayoutPreset'](arg1, arg2);
}

export function BuildStatusLine() {
  return window['go']['main']['App']['BuildStatusLine']();
}

export function CheckDirectoryConflict(arg1) {
  return window['go']['main']['App']['CheckDirectoryConflict'](arg1);
}

export function CheckWorktreePathConflict(arg1) {
  return window['go']['main']['App']['CheckWorktreePathConflict'](arg1);
}

export function CheckWorktreeStatus(arg1) {
  return window['go']['main']['App']['CheckWorktreeStatus'](arg1);
}

export function CleanupWorktree(arg1) {
  return window['go']['main']['App']['CleanupWorktree'](arg1);
}

export function CommitAndPushWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitAndPushWorktree'](arg1, arg2, arg3);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function CreateSessionWithExistingWorktree(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSessionWithExistingWorktree'](arg1, arg2, arg3, arg4);
}

export function CreateSessionWithWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSessionWithWorktree'](arg1, arg2, arg3);
}

export function DetachSession(arg1) {
  return window['go']['main']['App']['DetachSession'](arg1);
}

export function DevPanelCommitDiff(arg1, arg2) {
  return window['go']['main']['App']['DevPanelCommitDiff'](arg1, arg2);
}

export function DevPanelGitLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['DevPanelGitLog'](arg1, arg2, arg3);
}

export function DevPanelGitStatus(arg1) {
  return window['go']['main']['App']['DevPanelGitStatus'](arg1);
}

export function DevPanelListBranches(arg1) {
  return window['go']['main']['App']['DevPanelListBranches'](arg1);
}

export function DevPanelListDir(arg1, arg2) {
  return window['go']['main']['App']['DevPanelListDir'](arg1, arg2);
}

export function DevPanelReadFile(arg1, arg2) {
  return window['go']['main']['App']['DevPanelReadFile'](arg1, arg2);
}

export function DevPanelWorkingDiff(arg1) {
  return window['go']['main']['App']['DevPanelWorkingDiff'](arg1);
}

export function FocusPane(arg1) {
  return window['go']['main']['App']['FocusPane'](arg1);
}

export function GetActiveSession() {
  return window['go']['main']['App']['GetActiveSession']();
}

export function GetAllowedShells() {
  return window['go']['main']['App']['GetAllowedShells']();
}

export function GetClaudeEnvVarDescriptions() {
  return window['go']['main']['App']['GetClaudeEnvVarDescriptions']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigAndFlushWarnings() {
  return window['go']['main']['App']['GetConfigAndFlushWarnings']();
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetInputHistory() {
  return window['go']['main']['App']['GetInputHistory']();
}

export function GetInputHistoryFilePath() {
  return window['go']['main']['App']['GetInputHistoryFilePath']();
}

export function GetPaneEnv(arg1) {
  return window['go']['main']['App']['GetPaneEnv'](arg1);
}

export function GetPaneReplay(arg1) {
  return window['go']['main']['App']['GetPaneReplay'](arg1);
}

export function GetSessionEnv(arg1) {
  return window['go']['main']['App']['GetSessionEnv'](arg1);
}

export function GetSessionErrorLog() {
  return window['go']['main']['App']['GetSessionErrorLog']();
}

export function GetSessionLogFilePath() {
  return window['go']['main']['App']['GetSessionLogFilePath']();
}

export function GetValidationRules() {
  return window['go']['main']['App']['GetValidationRules']();
}

export function GetWebSocketURL() {
  return window['go']['main']['App']['GetWebSocketURL']();
}

export function InstallTmuxShim() {
  return window['go']['main']['App']['InstallTmuxShim']();
}

export function IsAgentTeamsAvailable() {
  return window['go']['main']['App']['IsAgentTeamsAvailable']();
}

export function IsGitRepository(arg1) {
  return window['go']['main']['App']['IsGitRepository'](arg1);
}

export function KillPane(arg1) {
  return window['go']['main']['App']['KillPane'](arg1);
}

export function KillSession(arg1, arg2) {
  return window['go']['main']['App']['KillSession'](arg1, arg2);
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListWorktreesByRepo(arg1) {
  return window['go']['main']['App']['ListWorktreesByRepo'](arg1);
}

export function LogFrontendEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontendEvent'](arg1, arg2, arg3);
}

export function PickSessionDirectory() {
  return window['go']['main']['App']['PickSessionDirectory']();
}

export function PromoteWorktreeToBranch(arg1, arg2) {
  return window['go']['main']['App']['PromoteWorktreeToBranch'](arg1, arg2);
}

export function QuickStartSession() {
  return window['go']['main']['App']['QuickStartSession']();
}

export function RenamePane(arg1, arg2) {
  return window['go']['main']['App']['RenamePane'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResizePane(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePane'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SendSyncInput(arg1, arg2) {
  return window['go']['main']['App']['SendSyncInput'](arg1, arg2);
}

export function SetActiveSession(arg1) {
  return window['go']['main']['App']['SetActiveSession'](arg1);
}

export function SplitPane(arg1, arg2) {
  return window['go']['main']['App']['SplitPane'](arg1, arg2);
}

export function SwapPanes(arg1, arg2) {
  return window['go']['main']['App']['SwapPanes'](arg1, arg2);
}
