// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {tmux} from '../models';
import {config} from '../models';
import {mcp} from '../models';
import {install} from '../models';
import {git} from '../models';
import {ipc} from '../models';

export function ApplyLayoutPreset(arg1:string,arg2:string):Promise<void>;

export function BuildStatusLine():Promise<string>;

export function CheckDirectoryConflict(arg1:string):Promise<string>;

export function CheckWorktreePathConflict(arg1:string):Promise<string>;

export function CheckWorktreeStatus(arg1:string):Promise<main.WorktreeStatus>;

export function CleanupWorktree(arg1:string):Promise<void>;

export function CommitAndPushWorktree(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:main.CreateSessionOptions):Promise<tmux.SessionSnapshot>;

export function CreateSessionWithExistingWorktree(arg1:string,arg2:string,arg3:string,arg4:main.CreateSessionOptions):Promise<tmux.SessionSnapshot>;

export function CreateSessionWithWorktree(arg1:string,arg2:string,arg3:main.WorktreeSessionOptions):Promise<tmux.SessionSnapshot>;

export function DeleteOrchestratorTeam(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteScheduler(arg1:string):Promise<void>;

export function DeleteSchedulerTemplate(arg1:string,arg2:string):Promise<void>;

export function DetachSession(arg1:string):Promise<void>;

export function DevPanelCommitDiff(arg1:string,arg2:string):Promise<string>;

export function DevPanelGitLog(arg1:string,arg2:number,arg3:boolean):Promise<Array<main.GitGraphCommit>>;

export function DevPanelGitStatus(arg1:string):Promise<main.GitStatusResult>;

export function DevPanelListBranches(arg1:string):Promise<Array<string>>;

export function DevPanelListDir(arg1:string,arg2:string):Promise<Array<main.FileEntry>>;

export function DevPanelReadFile(arg1:string,arg2:string):Promise<main.FileContent>;

export function DevPanelWorkingDiff(arg1:string):Promise<main.WorkingDiffResult>;

export function FocusPane(arg1:string):Promise<void>;

export function GetActiveSession():Promise<string>;

export function GetAllowedShells():Promise<Array<string>>;

export function GetClaudeEnvVarDescriptions():Promise<Record<string, string>>;

export function GetConfig():Promise<config.Config>;

export function GetConfigAndFlushWarnings():Promise<config.Config>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetInputHistory():Promise<Array<main.InputHistoryEntry>>;

export function GetInputHistoryFilePath():Promise<string>;

export function GetMCPDetail(arg1:string,arg2:string):Promise<mcp.Snapshot>;

export function GetPaneEnv(arg1:string):Promise<Record<string, string>>;

export function GetPaneProcessStatus(arg1:string):Promise<Array<main.PaneProcessStatus>>;

export function GetPaneReplay(arg1:string):Promise<string>;

export function GetSchedulerStatuses():Promise<Array<main.SchedulerEntryStatus>>;

export function GetSessionEnv(arg1:string):Promise<Record<string, string>>;

export function GetSessionErrorLog():Promise<Array<main.SessionLogEntry>>;

export function GetSessionLogFilePath():Promise<string>;

export function GetValidationRules():Promise<main.ValidationRules>;

export function GetWebSocketURL():Promise<string>;

export function InstallTmuxShim():Promise<install.ShimInstallResult>;

export function IsAgentTeamsAvailable():Promise<boolean>;

export function IsGitRepository(arg1:string):Promise<boolean>;

export function KillPane(arg1:string):Promise<void>;

export function KillSession(arg1:string,arg2:boolean):Promise<void>;

export function ListBranches(arg1:string):Promise<Array<string>>;

export function ListMCPServers(arg1:string):Promise<Array<mcp.Snapshot>>;

export function ListOrchestratorAgents(arg1:string):Promise<Array<main.OrchestratorAgent>>;

export function ListOrchestratorTasks(arg1:string):Promise<Array<main.OrchestratorTask>>;

export function ListSessions():Promise<Array<tmux.SessionSnapshot>>;

export function ListWorktreesByRepo(arg1:string):Promise<Array<git.WorktreeInfo>>;

export function LoadOrchestratorTeams(arg1:string):Promise<Array<main.OrchestratorTeamDefinition>>;

export function LoadSchedulerTemplates(arg1:string):Promise<Array<main.SchedulerTemplate>>;

export function LogFrontendEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenDirectoryInExplorer(arg1:string):Promise<void>;

export function PickSessionDirectory():Promise<string>;

export function PromoteWorktreeToBranch(arg1:string,arg2:string):Promise<void>;

export function QuickStartSession():Promise<tmux.SessionSnapshot>;

export function RenamePane(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ReorderOrchestratorTeams(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function ResizePane(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveMCPStdio(arg1:string,arg2:string):Promise<ipc.MCPStdioResolvePayload>;

export function ResumeScheduler(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveOrchestratorTeam(arg1:main.OrchestratorTeamDefinition,arg2:string):Promise<void>;

export function SaveSchedulerTemplate(arg1:string,arg2:main.SchedulerTemplate):Promise<void>;

export function SendChatMessage(arg1:string,arg2:string):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function SendSyncInput(arg1:string,arg2:string):Promise<void>;

export function SetActiveSession(arg1:string):Promise<void>;

export function SplitPane(arg1:string,arg2:boolean):Promise<string>;

export function StartOrchestratorTeam(arg1:main.StartOrchestratorTeamRequest):Promise<main.StartOrchestratorTeamResult>;

export function StartScheduler(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function StopAllSchedulers():Promise<void>;

export function StopScheduler(arg1:string):Promise<void>;

export function SwapPanes(arg1:string,arg2:string):Promise<void>;

export function ToggleMCPServer(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ToggleViewerSidebarMode():Promise<void>;
