// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMemberToUnaffiliatedTeam(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMemberToUnaffiliatedTeam'](arg1, arg2, arg3);
}

export function AddTaskSchedulerItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTaskSchedulerItem'](arg1, arg2, arg3, arg4, arg5);
}

export function ApplyLayoutPreset(arg1, arg2) {
  return window['go']['main']['App']['ApplyLayoutPreset'](arg1, arg2);
}

export function BootstrapMemberToPane(arg1) {
  return window['go']['main']['App']['BootstrapMemberToPane'](arg1);
}

export function BuildStatusLine() {
  return window['go']['main']['App']['BuildStatusLine']();
}

export function CheckDirectoryConflict(arg1) {
  return window['go']['main']['App']['CheckDirectoryConflict'](arg1);
}

export function CheckTaskSchedulerOrchestratorReady() {
  return window['go']['main']['App']['CheckTaskSchedulerOrchestratorReady']();
}

export function CheckWorktreePathConflict(arg1) {
  return window['go']['main']['App']['CheckWorktreePathConflict'](arg1);
}

export function CheckWorktreeStatus(arg1) {
  return window['go']['main']['App']['CheckWorktreeStatus'](arg1);
}

export function CleanupWorktree(arg1) {
  return window['go']['main']['App']['CleanupWorktree'](arg1);
}

export function CommitAndPushWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitAndPushWorktree'](arg1, arg2, arg3);
}

export function CreatePaneInSession(arg1) {
  return window['go']['main']['App']['CreatePaneInSession'](arg1);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function CreateSessionWithExistingWorktree(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSessionWithExistingWorktree'](arg1, arg2, arg3, arg4);
}

export function CreateSessionWithWorktree(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSessionWithWorktree'](arg1, arg2, arg3);
}

export function DeleteOrchestratorTeam(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteOrchestratorTeam'](arg1, arg2, arg3);
}

export function DeleteScheduler(arg1) {
  return window['go']['main']['App']['DeleteScheduler'](arg1);
}

export function DeleteSchedulerTemplate(arg1, arg2) {
  return window['go']['main']['App']['DeleteSchedulerTemplate'](arg1, arg2);
}

export function DetachSession(arg1) {
  return window['go']['main']['App']['DetachSession'](arg1);
}

export function DevPanelCommitDiff(arg1, arg2) {
  return window['go']['main']['App']['DevPanelCommitDiff'](arg1, arg2);
}

export function DevPanelGitCommit(arg1, arg2) {
  return window['go']['main']['App']['DevPanelGitCommit'](arg1, arg2);
}

export function DevPanelGitDiscard(arg1, arg2) {
  return window['go']['main']['App']['DevPanelGitDiscard'](arg1, arg2);
}

export function DevPanelGitFetch(arg1) {
  return window['go']['main']['App']['DevPanelGitFetch'](arg1);
}

export function DevPanelGitLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['DevPanelGitLog'](arg1, arg2, arg3);
}

export function DevPanelGitPull(arg1) {
  return window['go']['main']['App']['DevPanelGitPull'](arg1);
}

export function DevPanelGitPush(arg1) {
  return window['go']['main']['App']['DevPanelGitPush'](arg1);
}

export function DevPanelGitStage(arg1, arg2) {
  return window['go']['main']['App']['DevPanelGitStage'](arg1, arg2);
}

export function DevPanelGitStageAll(arg1) {
  return window['go']['main']['App']['DevPanelGitStageAll'](arg1);
}

export function DevPanelGitStatus(arg1) {
  return window['go']['main']['App']['DevPanelGitStatus'](arg1);
}

export function DevPanelGitUnstage(arg1, arg2) {
  return window['go']['main']['App']['DevPanelGitUnstage'](arg1, arg2);
}

export function DevPanelGitUnstageAll(arg1) {
  return window['go']['main']['App']['DevPanelGitUnstageAll'](arg1);
}

export function DevPanelListBranches(arg1) {
  return window['go']['main']['App']['DevPanelListBranches'](arg1);
}

export function DevPanelListDir(arg1, arg2) {
  return window['go']['main']['App']['DevPanelListDir'](arg1, arg2);
}

export function DevPanelReadFile(arg1, arg2) {
  return window['go']['main']['App']['DevPanelReadFile'](arg1, arg2);
}

export function DevPanelSearchFiles(arg1, arg2) {
  return window['go']['main']['App']['DevPanelSearchFiles'](arg1, arg2);
}

export function DevPanelWorkingDiff(arg1) {
  return window['go']['main']['App']['DevPanelWorkingDiff'](arg1);
}

export function EnsureUnaffiliatedTeam(arg1, arg2) {
  return window['go']['main']['App']['EnsureUnaffiliatedTeam'](arg1, arg2);
}

export function FocusPane(arg1) {
  return window['go']['main']['App']['FocusPane'](arg1);
}

export function GetActiveSession() {
  return window['go']['main']['App']['GetActiveSession']();
}

export function GetAllowedShells() {
  return window['go']['main']['App']['GetAllowedShells']();
}

export function GetClaudeEnvVarDescriptions() {
  return window['go']['main']['App']['GetClaudeEnvVarDescriptions']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigAndFlushWarnings() {
  return window['go']['main']['App']['GetConfigAndFlushWarnings']();
}

export function GetCurrentBranch(arg1) {
  return window['go']['main']['App']['GetCurrentBranch'](arg1);
}

export function GetInputHistory() {
  return window['go']['main']['App']['GetInputHistory']();
}

export function GetInputHistoryFilePath() {
  return window['go']['main']['App']['GetInputHistoryFilePath']();
}

export function GetMCPDetail(arg1, arg2) {
  return window['go']['main']['App']['GetMCPDetail'](arg1, arg2);
}

export function GetOrchestratorTaskDetail(arg1, arg2) {
  return window['go']['main']['App']['GetOrchestratorTaskDetail'](arg1, arg2);
}

export function GetPaneEnv(arg1) {
  return window['go']['main']['App']['GetPaneEnv'](arg1);
}

export function GetPaneProcessStatus(arg1) {
  return window['go']['main']['App']['GetPaneProcessStatus'](arg1);
}

export function GetPaneReplay(arg1) {
  return window['go']['main']['App']['GetPaneReplay'](arg1);
}

export function GetSchedulerStatuses() {
  return window['go']['main']['App']['GetSchedulerStatuses']();
}

export function GetSessionEnv(arg1) {
  return window['go']['main']['App']['GetSessionEnv'](arg1);
}

export function GetSessionErrorLog() {
  return window['go']['main']['App']['GetSessionErrorLog']();
}

export function GetSessionLogFilePath() {
  return window['go']['main']['App']['GetSessionLogFilePath']();
}

export function GetTaskSchedulerStatus() {
  return window['go']['main']['App']['GetTaskSchedulerStatus']();
}

export function GetValidationRules() {
  return window['go']['main']['App']['GetValidationRules']();
}

export function GetWebSocketURL() {
  return window['go']['main']['App']['GetWebSocketURL']();
}

export function InstallTmuxShim() {
  return window['go']['main']['App']['InstallTmuxShim']();
}

export function IsAgentTeamsAvailable() {
  return window['go']['main']['App']['IsAgentTeamsAvailable']();
}

export function IsGitRepository(arg1) {
  return window['go']['main']['App']['IsGitRepository'](arg1);
}

export function KillPane(arg1) {
  return window['go']['main']['App']['KillPane'](arg1);
}

export function KillSession(arg1, arg2) {
  return window['go']['main']['App']['KillSession'](arg1, arg2);
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListMCPServers(arg1) {
  return window['go']['main']['App']['ListMCPServers'](arg1);
}

export function ListOrchestratorAgents(arg1) {
  return window['go']['main']['App']['ListOrchestratorAgents'](arg1);
}

export function ListOrchestratorTasks(arg1) {
  return window['go']['main']['App']['ListOrchestratorTasks'](arg1);
}

export function ListOrphanedWorktrees(arg1) {
  return window['go']['main']['App']['ListOrphanedWorktrees'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListWorktreesByRepo(arg1) {
  return window['go']['main']['App']['ListWorktreesByRepo'](arg1);
}

export function LoadOrchestratorTeams(arg1) {
  return window['go']['main']['App']['LoadOrchestratorTeams'](arg1);
}

export function LoadSchedulerTemplates(arg1) {
  return window['go']['main']['App']['LoadSchedulerTemplates'](arg1);
}

export function LogFrontendEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontendEvent'](arg1, arg2, arg3);
}

export function OpenDirectoryInExplorer(arg1) {
  return window['go']['main']['App']['OpenDirectoryInExplorer'](arg1);
}

export function PauseTaskScheduler() {
  return window['go']['main']['App']['PauseTaskScheduler']();
}

export function PickSessionDirectory() {
  return window['go']['main']['App']['PickSessionDirectory']();
}

export function PromoteWorktreeToBranch(arg1, arg2) {
  return window['go']['main']['App']['PromoteWorktreeToBranch'](arg1, arg2);
}

export function QuickStartSession() {
  return window['go']['main']['App']['QuickStartSession']();
}

export function RecoverIMEWindowFocus() {
  return window['go']['main']['App']['RecoverIMEWindowFocus']();
}

export function RemoveTaskSchedulerItem(arg1) {
  return window['go']['main']['App']['RemoveTaskSchedulerItem'](arg1);
}

export function RenamePane(arg1, arg2) {
  return window['go']['main']['App']['RenamePane'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ReorderOrchestratorTeams(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderOrchestratorTeams'](arg1, arg2, arg3);
}

export function ReorderTaskSchedulerItems(arg1) {
  return window['go']['main']['App']['ReorderTaskSchedulerItems'](arg1);
}

export function ResizePane(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePane'](arg1, arg2, arg3);
}

export function ResolveMCPStdio(arg1, arg2) {
  return window['go']['main']['App']['ResolveMCPStdio'](arg1, arg2);
}

export function ResumeScheduler(arg1) {
  return window['go']['main']['App']['ResumeScheduler'](arg1);
}

export function ResumeTaskScheduler() {
  return window['go']['main']['App']['ResumeTaskScheduler']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveOrchestratorTeam(arg1, arg2) {
  return window['go']['main']['App']['SaveOrchestratorTeam'](arg1, arg2);
}

export function SaveSchedulerTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveSchedulerTemplate'](arg1, arg2);
}

export function SaveUnaffiliatedTeamMembers(arg1, arg2) {
  return window['go']['main']['App']['SaveUnaffiliatedTeamMembers'](arg1, arg2);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SendSyncInput(arg1, arg2) {
  return window['go']['main']['App']['SendSyncInput'](arg1, arg2);
}

export function SetActiveSession(arg1) {
  return window['go']['main']['App']['SetActiveSession'](arg1);
}

export function SplitPane(arg1, arg2) {
  return window['go']['main']['App']['SplitPane'](arg1, arg2);
}

export function StartOrchestratorTeam(arg1) {
  return window['go']['main']['App']['StartOrchestratorTeam'](arg1);
}

export function StartScheduler(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartScheduler'](arg1, arg2, arg3, arg4, arg5);
}

export function StartTaskScheduler(arg1, arg2) {
  return window['go']['main']['App']['StartTaskScheduler'](arg1, arg2);
}

export function StopAllSchedulers() {
  return window['go']['main']['App']['StopAllSchedulers']();
}

export function StopScheduler(arg1) {
  return window['go']['main']['App']['StopScheduler'](arg1);
}

export function StopTaskScheduler() {
  return window['go']['main']['App']['StopTaskScheduler']();
}

export function SwapPanes(arg1, arg2) {
  return window['go']['main']['App']['SwapPanes'](arg1, arg2);
}

export function ToggleMCPServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2, arg3);
}

export function ToggleViewerSidebarMode() {
  return window['go']['main']['App']['ToggleViewerSidebarMode']();
}

export function UpdateTaskSchedulerItem(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTaskSchedulerItem'](arg1, arg2, arg3, arg4, arg5, arg6);
}
