// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {orchestrator} from '../models';
import {main} from '../models';
import {worktree} from '../models';
import {tmux} from '../models';
import {devpanel} from '../models';
import {config} from '../models';
import {inputhistory} from '../models';
import {mcp} from '../models';
import {scheduler} from '../models';
import {sessionlog} from '../models';
import {singletaskrunner} from '../models';
import {taskscheduler} from '../models';
import {usagedashboard} from '../models';
import {install} from '../models';
import {git} from '../models';
import {promptpresets} from '../models';
import {ipc} from '../models';

export function AddMemberToUnaffiliatedTeam(arg1:orchestrator.TeamMember,arg2:string,arg3:string):Promise<void>;

export function AddSingleTaskRunnerItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<void>;

export function AddTaskSchedulerItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<void>;

export function ApplyLayoutPreset(arg1:string,arg2:string):Promise<void>;

export function BootstrapMemberToPane(arg1:orchestrator.BootstrapMemberToPaneRequest):Promise<orchestrator.BootstrapMemberToPaneResult>;

export function BuildStatusLine():Promise<string>;

export function CheckDirectoryConflict(arg1:string):Promise<string>;

export function CheckTaskSchedulerOrchestratorReady(arg1:string):Promise<main.TaskSchedulerOrchestratorReadiness>;

export function CheckWorktreePathConflict(arg1:string):Promise<string>;

export function CheckWorktreeStatus(arg1:string):Promise<worktree.WorktreeStatus>;

export function CleanupWorktree(arg1:string):Promise<void>;

export function CommitAndPushWorktree(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreatePaneInSession(arg1:string):Promise<string>;

export function CreateSession(arg1:string,arg2:string,arg3:main.CreateSessionOptions):Promise<tmux.SessionSnapshot>;

export function CreateSessionWithExistingWorktree(arg1:string,arg2:string,arg3:string,arg4:main.CreateSessionOptions):Promise<tmux.SessionSnapshot>;

export function CreateSessionWithWorktree(arg1:string,arg2:string,arg3:worktree.WorktreeSessionOptions):Promise<tmux.SessionSnapshot>;

export function DeleteOrchestratorTeam(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeletePromptPreset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteScheduler(arg1:string):Promise<void>;

export function DeleteSchedulerTemplate(arg1:string,arg2:string):Promise<void>;

export function DetachSession(arg1:string):Promise<void>;

export function DevPanelCommitDiff(arg1:string,arg2:string):Promise<string>;

export function DevPanelCreateDirectory(arg1:string,arg2:string):Promise<void>;

export function DevPanelCreateFile(arg1:string,arg2:string):Promise<devpanel.WriteFileResult>;

export function DevPanelDeleteFile(arg1:string,arg2:string):Promise<void>;

export function DevPanelGetFileInfo(arg1:string,arg2:string):Promise<devpanel.FileMetadata>;

export function DevPanelGitCommit(arg1:string,arg2:string):Promise<devpanel.CommitResult>;

export function DevPanelGitDiscard(arg1:string,arg2:string):Promise<void>;

export function DevPanelGitFetch(arg1:string):Promise<void>;

export function DevPanelGitLog(arg1:string,arg2:number,arg3:boolean):Promise<Array<devpanel.GitGraphCommit>>;

export function DevPanelGitPull(arg1:string):Promise<devpanel.PullResult>;

export function DevPanelGitPush(arg1:string):Promise<devpanel.PushResult>;

export function DevPanelGitStage(arg1:string,arg2:string):Promise<void>;

export function DevPanelGitStageAll(arg1:string):Promise<void>;

export function DevPanelGitStatus(arg1:string):Promise<devpanel.GitStatusResult>;

export function DevPanelGitUnstage(arg1:string,arg2:string):Promise<void>;

export function DevPanelGitUnstageAll(arg1:string):Promise<void>;

export function DevPanelListBranches(arg1:string):Promise<Array<string>>;

export function DevPanelListDir(arg1:string,arg2:string):Promise<Array<devpanel.FileEntry>>;

export function DevPanelReadBinary(arg1:string,arg2:string):Promise<devpanel.BinaryFileContent>;

export function DevPanelReadFile(arg1:string,arg2:string):Promise<devpanel.FileContent>;

export function DevPanelRenameFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DevPanelSearchFiles(arg1:string,arg2:string):Promise<Array<devpanel.SearchFileResult>>;

export function DevPanelSqliteExportCSV(arg1:string,arg2:string,arg3:string,arg4:string):Promise<devpanel.SqliteExportResult>;

export function DevPanelSqliteListTables(arg1:string,arg2:string):Promise<Array<devpanel.SqliteTableInfo>>;

export function DevPanelSqliteQueryTable(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<devpanel.SqliteQueryResult>;

export function DevPanelStartWatcher(arg1:string):Promise<void>;

export function DevPanelStopWatcher(arg1:string):Promise<void>;

export function DevPanelWorkingDiff(arg1:string):Promise<devpanel.WorkingDiffResult>;

export function DevPanelWriteFile(arg1:string,arg2:string,arg3:string):Promise<devpanel.WriteFileResult>;

export function EnlistPane(arg1:orchestrator.EnlistPaneRequest):Promise<orchestrator.EnlistPaneResult>;

export function EnsureUnaffiliatedTeam(arg1:string,arg2:string):Promise<orchestrator.TeamDefinition>;

export function FocusPane(arg1:string):Promise<void>;

export function GetActiveSession():Promise<string>;

export function GetAllowedShells():Promise<Array<string>>;

export function GetClaudeEnvVarDescriptions():Promise<Record<string, string>>;

export function GetConfig():Promise<config.Config>;

export function GetConfigAndFlushWarnings():Promise<config.Config>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetInputHistory():Promise<Array<inputhistory.Entry>>;

export function GetInputHistoryFilePath():Promise<string>;

export function GetMCPDetail(arg1:string,arg2:string):Promise<mcp.Snapshot>;

export function GetOrchestratorTaskDetail(arg1:string,arg2:string):Promise<main.OrchestratorTaskDetail>;

export function GetPaneEnv(arg1:string):Promise<Record<string, string>>;

export function GetPaneProcessStatus(arg1:string):Promise<Array<main.PaneProcessStatus>>;

export function GetPaneReplay(arg1:string):Promise<string>;

export function GetSchedulerStatuses():Promise<Array<scheduler.EntryStatus>>;

export function GetSessionEnlistmentContext(arg1:string):Promise<orchestrator.SessionEnlistmentContext>;

export function GetSessionEnv(arg1:string):Promise<Record<string, string>>;

export function GetSessionErrorLog():Promise<Array<sessionlog.Entry>>;

export function GetSessionLogFilePath():Promise<string>;

export function GetSingleTaskRunnerClearDelay(arg1:string):Promise<number>;

export function GetSingleTaskRunnerStatus(arg1:string):Promise<singletaskrunner.QueueStatus>;

export function GetTaskSchedulerSettings():Promise<config.TaskSchedulerConfig>;

export function GetTaskSchedulerStatus(arg1:string):Promise<taskscheduler.QueueStatus>;

export function GetUsageDashboard(arg1:string,arg2:string,arg3:boolean):Promise<usagedashboard.UsageDashboardSnapshot>;

export function GetValidationRules():Promise<main.ValidationRules>;

export function GetWebSocketURL():Promise<string>;

export function InstallTmuxShim():Promise<install.ShimInstallResult>;

export function IsAgentTeamsAvailable():Promise<boolean>;

export function IsGitRepository(arg1:string):Promise<boolean>;

export function KillPane(arg1:string):Promise<void>;

export function KillSession(arg1:string,arg2:boolean):Promise<void>;

export function ListBranches(arg1:string):Promise<Array<string>>;

export function ListMCPServers(arg1:string):Promise<Array<mcp.Snapshot>>;

export function ListOrchestratorAgents(arg1:string):Promise<Array<main.OrchestratorAgent>>;

export function ListOrchestratorTasks(arg1:string):Promise<Array<main.OrchestratorTask>>;

export function ListOrphanedWorktrees(arg1:string):Promise<Array<worktree.OrphanedWorktree>>;

export function ListSessions():Promise<Array<tmux.SessionSnapshot>>;

export function ListWorktreesByRepo(arg1:string):Promise<Array<git.WorktreeInfo>>;

export function LoadOrchestratorTeams(arg1:string):Promise<Array<orchestrator.TeamDefinition>>;

export function LoadPromptPresets(arg1:string):Promise<promptpresets.LoadResult>;

export function LoadSchedulerTemplates(arg1:string):Promise<Array<scheduler.Template>>;

export function LoadSessionMemo(arg1:string):Promise<string>;

export function LogFrontendEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenDirectoryInExplorer(arg1:string):Promise<void>;

export function PauseTaskScheduler(arg1:string):Promise<void>;

export function PickSessionDirectory():Promise<string>;

export function PromoteWorktreeToBranch(arg1:string,arg2:string):Promise<void>;

export function QuickStartSession():Promise<tmux.SessionSnapshot>;

export function RecoverIMEWindowFocus():Promise<void>;

export function RemoveSingleTaskRunnerItem(arg1:string,arg2:string):Promise<void>;

export function RemoveTaskSchedulerItem(arg1:string,arg2:string):Promise<void>;

export function RenamePane(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ReorderOrchestratorTeams(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function ReorderPromptPresets(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function ReorderSingleTaskRunnerItems(arg1:string,arg2:Array<string>):Promise<void>;

export function ReorderTaskSchedulerItems(arg1:string,arg2:Array<string>):Promise<void>;

export function ResizePane(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveMCPStdio(arg1:string,arg2:string):Promise<ipc.MCPStdioResolvePayload>;

export function ResumeScheduler(arg1:string):Promise<void>;

export function ResumeTaskScheduler(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveOrchestratorTeam(arg1:orchestrator.TeamDefinition,arg2:string):Promise<void>;

export function SavePromptPreset(arg1:promptpresets.PromptPreset,arg2:string):Promise<void>;

export function SaveSchedulerTemplate(arg1:string,arg2:scheduler.Template):Promise<void>;

export function SaveSessionMemo(arg1:string,arg2:string):Promise<void>;

export function SaveTaskSchedulerSettings(arg1:config.TaskSchedulerConfig):Promise<void>;

export function SaveUnaffiliatedTeamMembers(arg1:Array<orchestrator.TeamMember>,arg2:string):Promise<void>;

export function SendChatMessage(arg1:string,arg2:string):Promise<void>;

export function SendDiffReview(arg1:string,arg2:string):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function SendSyncInput(arg1:string,arg2:string):Promise<void>;

export function SetActiveSession(arg1:string):Promise<void>;

export function SetSingleTaskRunnerClearDelay(arg1:string,arg2:number):Promise<void>;

export function SplitPane(arg1:string,arg2:boolean):Promise<string>;

export function StartAutoStartCommand(arg1:string,arg2:config.AutoStartCommand):Promise<string>;

export function StartOrchestratorTeam(arg1:orchestrator.StartTeamRequest):Promise<orchestrator.StartTeamResult>;

export function StartScheduler(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function StartSingleTaskRunner(arg1:string):Promise<void>;

export function StartTaskScheduler(arg1:string,arg2:taskscheduler.QueueConfig,arg3:Array<taskscheduler.QueueItem>):Promise<void>;

export function StopAllSchedulers():Promise<void>;

export function StopScheduler(arg1:string):Promise<void>;

export function StopSingleTaskRunner(arg1:string):Promise<void>;

export function StopTaskScheduler(arg1:string):Promise<void>;

export function SwapPanes(arg1:string,arg2:string):Promise<void>;

export function ToggleMCPServer(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ToggleViewerSidebarMode():Promise<void>;

export function UpdateSingleTaskRunnerItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:string):Promise<void>;

export function UpdateTaskSchedulerItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:string):Promise<void>;
