import {isValidElement, memo, useCallback, useEffect, useMemo, useState, type MouseEvent, type ReactNode} from "react";
import {getLanguage, translate} from "../../../../i18n";
import {useNotificationStore} from "../../../../stores/notificationStore";
import {sanitizeCssColor} from "../../../../utils/cssUtils";
import {logFrontendEventSafe} from "../../../../utils/logFrontendEventSafe";
import {notifyLinkOpenFailure} from "../../../../utils/notifyUtils";
import {sanitizeHref, SCHEME_PATTERN} from "../../../../utils/sanitizeHref";
import ReactMarkdown, {defaultUrlTransform} from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import {unified, type PluggableList} from "unified";
import type {Components} from "react-markdown";
import {visit} from "unist-util-visit";
import type {Heading, Root} from "mdast";
import {toString} from "mdast-util-to-string";
import {useShikiHighlight} from "../../../../hooks/useShikiHighlight";
import {BrowserOpenURL} from "../../../../../wailsjs/runtime";
import {ChevronIcon} from "../../icons/ChevronIcon";

interface MarkdownPreviewProps {
    readonly content: string;
    readonly rehypePlugins?: PluggableList;
    readonly codeBlockRenderer?: (props: MarkdownCodeBlockRendererProps) => ReactNode;
}

const EMPTY_REHYPE_PLUGINS: PluggableList = [];

const MARKDOWN_OUTLINE_NAV_ID = "markdown-outline-nav";

type MarkdownHeadingDepth = Heading["depth"];

interface MarkdownHeading {
    /** Unique slug within this document, generated by createHeadingSlugger. */
    readonly id: string;
    readonly text: string;
    readonly depth: MarkdownHeadingDepth;
}

function translateViewerText(key: string, jaText: string, enText: string): string {
    return translate(key, getLanguage() === "ja" ? jaText : enText);
}

// ── Shiki-highlighted code block for fenced code ──

function logExternalLinkOpenError(href: string, err: unknown): void {
    notifyLinkOpenFailure();
    console.warn("[markdown] failed to open external link", href, err);
}

function openExternalLink(href: string): void {
    try {
        BrowserOpenURL(href);
    } catch (err: unknown) {
        logExternalLinkOpenError(href, err);
    }
}

function warnMissingHeadingTarget(id: string): void {
    console.warn("[markdown] heading target not found", id);
    logFrontendEventSafe("warn", `Heading target not found: ${id}`, "MarkdownPreview");
    useNotificationStore.getState().addNotification(
        translateViewerText(
            "viewer.markdown.headingTarget.missing",
            "見出しへ移動できませんでした",
            "Failed to jump to section",
        ),
        "warn",
    );
}

function scrollToHeadingOrReport(id: string): void {
    if (!scrollToHeading(id)) {
        warnMissingHeadingTarget(id);
    }
}

// Generates URL-safe heading slugs in document order.
// Uses NFKC normalization so compatibility characters collapse before punctuation stripping.
// Duplicate headings are disambiguated by appending -1, -2, ... while also avoiding
// collisions with headings that already end in numeric suffixes (for example "intro-1").
// Falls back to "section" when the normalized heading becomes empty.
function createHeadingSlugger(): (text: string) => string {
    const usedSlugs = new Set<string>();
    return (text: string) => {
        const base = text
            .trim()
            .normalize("NFKC")
            .toLowerCase()
            .replace(/[^\p{Letter}\p{Number}\s-]/gu, " ")
            .trim()
            .replace(/\s+/g, "-") || "section";
        let slug = base;
        let counter = 1;
        while (usedSlugs.has(slug)) {
            slug = `${base}-${counter}`;
            counter++;
        }
        usedSlugs.add(slug);
        return slug;
    };
}

// Outline extraction and remarkHeadingAnchors must stay in sync: the outline buttons and
// rendered heading IDs are produced in separate passes, but both rely on the same heading
// text filtering and document order to generate matching slugs.
function visitMarkdownHeadings(tree: Root, visitor: (node: Heading, text: string) => void): void {
    visit(tree, "heading", (node: Heading) => {
        const text = toString(node).trim();
        if (text === "") {
            return;
        }

        visitor(node, text);
    });
}

function buildMarkdownHeadings(content: string): readonly MarkdownHeading[] {
    const tree = unified()
        .use(remarkParse)
        .use(remarkGfm, {singleTilde: false})
        .parse(content) as Root;
    const nextHeadingID = createHeadingSlugger();
    const headings: MarkdownHeading[] = [];

    visitMarkdownHeadings(tree, (node, text) => {
        headings.push({
            id: nextHeadingID(text),
            text,
            depth: node.depth,
        });
    });

    return headings;
}

function remarkHeadingAnchors() {
    return (tree: Root) => {
        try {
            const nextHeadingID = createHeadingSlugger();
            visitMarkdownHeadings(tree, (node, text) => {
                const id = nextHeadingID(text);
                node.data ??= {};
                // hProperties are forwarded to the rendered heading element during the
                // remark -> rehype transform, so this is the supported place to inject id=.
                node.data.hProperties = {
                    ...(node.data.hProperties ?? {}),
                    id,
                };
            });
        } catch (err: unknown) {
            console.warn("[markdown] failed to assign heading anchors", err);
        }
    };
}

const MARKDOWN_REMARK_PLUGINS: PluggableList = [
    [remarkGfm, {singleTilde: false}],
    remarkHeadingAnchors,
];

// Maximum recursion depth for extractTextContent (depth starts at 0, so max traversed depth is 49).
// react-markdown output is typically shallow, but this guards against
// pathologically nested markdown structures.
const EXTRACT_TEXT_MAX_DEPTH = 50;

// Recursively flatten markdown code children into plain text.
// Handles nested fragments/spans produced by remark/rehype plugins.
function extractTextContent(node: ReactNode, depth: number = 0): string {
    if (depth >= EXTRACT_TEXT_MAX_DEPTH) {
        // In production, silently returns "" (truncated text).
        // Depth 50 is well above typical markdown nesting (rarely exceeds 10 levels).
        // If this limit is reached, the Shiki code block will receive truncated source,
        // resulting in partial highlighting — acceptable degradation for pathological input.
        console.warn("[MarkdownPreview] extractTextContent: recursion depth limit reached, text may be truncated");
        return "";
    }
    if (typeof node === "string" || typeof node === "number") {
        return String(node);
    }
    if (typeof node === "boolean" || node == null) {
        return "";
    }
    if (Array.isArray(node)) {
        return node.map((item) => extractTextContent(item, depth + 1)).join("");
    }
    if (isValidElement<{ children?: ReactNode }>(node)) {
        return extractTextContent(node.props.children, depth + 1);
    }
    return "";
}

interface ShikiCodeBlockProps {
    className?: string;
    children?: ReactNode;
    code?: string;
}

const ShikiCodeBlock = memo(function ShikiCodeBlock({className, children, code: providedCode}: ShikiCodeBlockProps) {
    // Extract language from className (e.g., "language-typescript" -> "typescript").
    const lang = className?.match(/\blanguage-(\S+)/)?.[1] ?? "";
    const code = providedCode ?? extractTextContent(children).replace(/\r?\n$/, "");

    // Reuse the shared hook instead of reimplementing the async highlight lifecycle.
    // Pass lang directly (3rd arg) since we already have the language ID from the CSS class.
    const {tokens} = useShikiHighlight(code || undefined, undefined, lang || undefined);

    if (tokens) {
        return (
            <code className={className}>
                {tokens.map((line, lineIndex) => (
                    <span key={`line-${lineIndex}`}>
                        {line.map((token, tokenIndex) => (
                            <span key={`token-${lineIndex}-${tokenIndex}`}
                                  style={{color: sanitizeCssColor(token.color)}}>
                                {token.content}
                            </span>
                        ))}
                        {lineIndex < tokens.length - 1 ? "\n" : null}
                    </span>
                ))}
            </code>
        );
    }

    // Fallback: plain text while Shiki loads.
    return <code className={className}>{children}</code>;
});

// ── Custom components for react-markdown ──

export interface MarkdownCodeBlockRendererProps {
    readonly className?: string;
    readonly code: string;
}

function scrollToHeading(id: string): boolean {
    const target = globalThis.document?.getElementById(id);
    if (!(target instanceof HTMLElement)) {
        return false;
    }

    target.scrollIntoView({
        behavior: "smooth",
        block: "start",
    });
    return true;
}

function createMarkdownComponents(
    codeBlockRenderer?: (props: MarkdownCodeBlockRendererProps) => ReactNode,
): Components {
    return {
        a({href, children, ...props}) {
            const {node: _node, rel: _rel, target: _target, ...domProps} = props as typeof props & {
                node?: unknown;
                rel?: string;
                target?: string;
            };

            const safeHref = sanitizeHref(href);
            if (!safeHref) {
                return <span className="md-preview-unsafe-link">{children}</span>;
            }

            const isAnchor = safeHref.startsWith("#");
            const isRelative = safeHref.startsWith("/") || safeHref.startsWith("./") || safeHref.startsWith("../");
            const isExternal = SCHEME_PATTERN.test(safeHref);
            const handleLinkClick = (event: MouseEvent<HTMLAnchorElement>) => {
                if (isAnchor) {
                    event.preventDefault();
                    scrollToHeadingOrReport(safeHref.slice(1));
                    return;
                }
                if (isRelative) {
                    // Relative paths cannot be resolved inside the Wails WebView without
                    // workspace context for the currently previewed markdown file.
                    event.preventDefault();
                    if (import.meta.env.DEV) {
                        console.warn("[DEBUG-markdown] Internal link navigation suppressed:", safeHref);
                    }
                    return;
                }
                if (isExternal) {
                    event.preventDefault();
                    openExternalLink(safeHref);
                    return;
                }
                // Scheme-less URLs (e.g., "foo/bar") that are neither internal nav nor external.
                // Prevent default navigation to avoid unintended Wails webview navigation.
                event.preventDefault();
                if (import.meta.env.DEV) {
                    console.warn("[DEBUG-markdown] Scheme-less link navigation suppressed:", safeHref);
                }
            };

            // #111: Provide visual feedback only for links that are intentionally blocked inside
            // the desktop app, while keeping navigable anchors and external links unmarked.
            const disabledLinkTitle = isAnchor
                ? undefined
                : isRelative
                ? translateViewerText(
                    "viewer.markdown.link.desktopBlocked",
                    "このリンクはデスクトップアプリ内では開けません (This link cannot be opened in the desktop app)",
                    "This link cannot be opened in the desktop app",
                )
                : isExternal
                    ? undefined
                    : translateViewerText(
                        "viewer.markdown.link.unsupportedFormat",
                        "このリンク形式はプレビュー内では開けません (Unsupported link format in preview)",
                        "Unsupported link format in preview",
                    );

            // data-original-href: preserves the original href for debugging and potential future
            // features (e.g., file-tree navigation). Not referenced by CSS or JS currently.
            return (
                <a
                    href={isExternal ? safeHref : undefined}
                    {...domProps}
                    onClick={handleLinkClick}
                    rel={isExternal ? "noopener noreferrer nofollow" : undefined}
                    target={isExternal ? "_blank" : undefined}
                    data-original-href={isRelative ? safeHref : undefined}
                    aria-label={
                        isAnchor
                            ? translateViewerText(
                                "viewer.markdown.link.aria.inPage",
                                `ページ内リンク: ${safeHref}`,
                                `In-page link: ${safeHref}`,
                            )
                            : isRelative
                            ? translateViewerText(
                                "viewer.markdown.link.aria.blocked",
                                `アプリ内で開けないリンク: ${safeHref}`,
                                `Blocked in-app link: ${safeHref}`,
                            )
                            : isExternal
                                ? translateViewerText(
                                    "viewer.markdown.link.aria.external",
                                    `外部リンク: ${safeHref}`,
                                    `External link: ${safeHref}`,
                                )
                                : translateViewerText(
                                    "viewer.markdown.link.aria.unsupported",
                                    `プレビューで未対応のリンク: ${safeHref}`,
                                    `Blocked unsupported link: ${safeHref}`,
                                )
                    }
                    title={disabledLinkTitle}
                    className={isRelative ? "md-preview-disabled-link" : undefined}
                >
                    {children}
                </a>
            );
        },
        img({src, alt, ...props}) {
            const trustedBlobSrc = typeof src === "string" && src.startsWith("blob:")
                ? src
                : null;
            const {node: _node, ...domProps} = props as typeof props & { node?: unknown };
            const safeSrc = trustedBlobSrc ?? sanitizeHref(src);
            const hasExplicitScheme = safeSrc ? SCHEME_PATTERN.test(safeSrc) : false;
            const isResolvedLocalBlob = safeSrc?.startsWith("blob:") === true;
            // SECURITY: Only local/relative image paths are allowed. URI schemes
            // (http:, https:, file:, data:, ftp:, ws:, etc.; RFC 3986 forms) are
            // blocked to prevent network requests from markdown content.
            // blob: URLs are also allowed because they are origin-local object URLs
            // rather than network fetches, and the file-view image pipeline relies
            // on them for session-local image previews.
            // Relative paths (./foo, ../bar)
            // resolve within Wails WebView2's app asset boundary.
            // Fragment-only URLs (#anchor) make no sense as image sources and are blocked.
            // While sanitizeHref passes them through for regular links, images need an actual path.
            if (!safeSrc || (hasExplicitScheme && !isResolvedLocalBlob) || safeSrc.startsWith("#")) {
                return <span className="md-preview-unsafe-img" role="img" aria-label="Image blocked for security">[image blocked]</span>;
            }
            return <img src={safeSrc} alt={alt ?? ""} {...domProps}/>;
        },
        code({className, children, ...props}) {
            const {node: _node, inline: _inline, ...domProps} = props as typeof props & {
                node?: unknown;
                inline?: unknown;
            };
            // Block code (fenced with language) -> Shiki highlighting.
            const isBlock = className?.startsWith("language-");
            if (isBlock) {
                const code = extractTextContent(children).replace(/\r?\n$/, "");
                const customBlock = codeBlockRenderer?.({className, code});
                if (customBlock) {
                    return customBlock;
                }
                return <ShikiCodeBlock className={className} code={code}>{children}</ShikiCodeBlock>;
            }
            // Inline code -> plain rendering.
            return <code className={className} {...domProps}>{children}</code>;
        },
        pre({children, ...props}) {
            const {node: _node, ...domProps} = props as typeof props & { node?: unknown };
            return <pre className="md-preview-code-block" {...domProps}>{children}</pre>;
        },
    };
}

/**
 * Renders markdown content with GFM support and Shiki-highlighted code blocks.
 * Memoized to prevent unnecessary re-renders when parent state changes.
 */
export const MarkdownPreview = memo(function MarkdownPreview({
    content,
    rehypePlugins = EMPTY_REHYPE_PLUGINS,
    codeBlockRenderer,
}: MarkdownPreviewProps) {
    const [isOutlineCollapsed, setIsOutlineCollapsed] = useState(false);
    const headings = useMemo(() => {
        try {
            return buildMarkdownHeadings(content);
        } catch (err: unknown) {
            console.warn("[markdown] failed to build heading outline", err);
            return [];
        }
    }, [content]);
    const hasOutline = headings.length > 0;
    const markdownComponents = useMemo(
        () => createMarkdownComponents(codeBlockRenderer),
        [codeBlockRenderer],
    );
    useEffect(() => {
        setIsOutlineCollapsed(false);
    }, [content]);
    const handleOutlineToggle = useCallback(() => {
        setIsOutlineCollapsed((previous) => !previous);
    }, []);
    const handleOutlineJump = useCallback((event: MouseEvent<HTMLButtonElement>) => {
        const id = event.currentTarget.dataset.headingId;
        if (!id) {
            return;
        }
        scrollToHeadingOrReport(id);
    }, []);
    const markdownUrlTransform = (url: string) => (
        url.startsWith("blob:") ? url : defaultUrlTransform(url)
    );

    return (
        <div className="md-preview-body">
            <div className="md-preview-layout">
                <div className="md-preview-main">
                    <ReactMarkdown
                        remarkPlugins={MARKDOWN_REMARK_PLUGINS}
                        rehypePlugins={rehypePlugins}
                        components={markdownComponents}
                        urlTransform={markdownUrlTransform}
                    >
                        {content}
                    </ReactMarkdown>
                </div>
                {hasOutline ? (
                    <aside
                        className={`md-preview-outline${isOutlineCollapsed ? " is-collapsed" : ""}`}
                        aria-label={translateViewerText(
                            "viewer.markdown.outline.aria.region",
                            "Markdown アウトライン",
                            "Markdown outline",
                        )}
                    >
                        {isOutlineCollapsed ? (
                            <button
                                type="button"
                                className="md-preview-outline-collapsed-toggle"
                                onClick={handleOutlineToggle}
                                title={translateViewerText(
                                    "viewer.markdown.outline.expand",
                                    "アウトラインを展開",
                                    "Expand outline",
                                )}
                                aria-label={translateViewerText(
                                    "viewer.markdown.outline.expand",
                                    "アウトラインを展開",
                                    "Expand outline",
                                )}
                                aria-expanded={false}
                            >
                                <span className="md-preview-outline-chevron is-collapsed">
                                    <ChevronIcon size={12}/>
                                </span>
                            </button>
                        ) : (
                            <div className="md-preview-outline-panel">
                                <div className="md-preview-outline-header">
                                    <span className="md-preview-outline-title">
                                        {translateViewerText(
                                            "viewer.markdown.outline.title",
                                            "アウトライン",
                                            "Outline",
                                        )}
                                    </span>
                                    <button
                                        type="button"
                                        className="md-preview-outline-toggle"
                                        onClick={handleOutlineToggle}
                                        title={translateViewerText(
                                            "viewer.markdown.outline.collapse",
                                            "アウトラインを折りたたむ",
                                            "Collapse outline",
                                        )}
                                        aria-label={translateViewerText(
                                            "viewer.markdown.outline.collapse",
                                            "アウトラインを折りたたむ",
                                            "Collapse outline",
                                        )}
                                        aria-expanded={true}
                                        aria-controls={MARKDOWN_OUTLINE_NAV_ID}
                                    >
                                        <span className="md-preview-outline-chevron">
                                            <ChevronIcon size={12}/>
                                        </span>
                                    </button>
                                </div>
                                <nav
                                    id={MARKDOWN_OUTLINE_NAV_ID}
                                    className="md-preview-outline-nav"
                                    aria-label={translateViewerText(
                                        "viewer.markdown.outline.aria.sections",
                                        "ドキュメントの見出し一覧",
                                        "Document sections",
                                    )}
                                >
                                    {headings.map((heading) => (
                                        <button
                                            key={heading.id}
                                            type="button"
                                            className={`md-preview-outline-item depth-${heading.depth}`}
                                            data-heading-id={heading.id}
                                            onClick={handleOutlineJump}
                                            title={heading.text}
                                        >
                                            {heading.text}
                                        </button>
                                    ))}
                                </nav>
                            </div>
                        )}
                    </aside>
                ) : null}
            </div>
        </div>
    );
});
