// Re-export from auto-generated Wails bindings (single source of truth).
import {devpanel} from "../../../../../wailsjs/go/models";

export type WorkingDiffFile = devpanel.WorkingDiffFile;
export type WorkingDiffResult = devpanel.WorkingDiffResult;

// DiffTreeNode is a frontend-only view model (not generated by Wails).
interface DiffTreeNodeBase {
    readonly name: string;
    readonly path: string;
    readonly depth: number;
}

export interface DiffDirectoryNode extends DiffTreeNodeBase {
    readonly isDir: true;
    readonly isExpanded: boolean;
}

export interface DiffFileNode extends DiffTreeNodeBase {
    readonly isDir: false;
    readonly file: WorkingDiffFile;
}

export type DiffTreeNode = DiffDirectoryNode | DiffFileNode;
