// Re-export from auto-generated Wails bindings (single source of truth).
import {main} from "../../../../../wailsjs/go/models";

export type WorkingDiffFile = main.WorkingDiffFile;
export type WorkingDiffResult = main.WorkingDiffResult;

// DiffTreeNode is a frontend-only view model (not generated by Wails).
export interface DiffTreeNode {
    name: string;
    path: string;
    isDir: boolean;
    depth: number;
    isExpanded: boolean;
    file?: WorkingDiffFile;
}
