/**
 * S-23: api.ts エラーハンドリング方針
 *
 * このモジュールは Wails バインディングを薄くラップするだけの責務を持つ。
 * エラーハンドリングは呼び出し元（コンポーネント / フック）で行う。
 *
 * 統一パターン:
 *   void api.SomeMethod(arg).catch((err) => {
 *     console.warn("[context] operation failed", err);
 *   });
 *
 * - 結果を使う場合は `await api.SomeMethod(arg)` で try/catch を書く。
 * - fire-and-forget の場合は `void api.SomeMethod(arg).catch(...)` を使う。
 * - console.warn の prefix は "[コンテキスト名]" で統一する。
 * - このファイル内では Promise を握り潰さない。Promise はそのまま返却する。
 */
import {
    AddSingleTaskRunnerItem,
    ApplyLayoutPreset,
    BuildStatusLine,
    CheckDirectoryConflict,
    CheckWorktreePathConflict,
    CheckWorktreeStatus,
    CleanupWorktree,
    CommitAndPushWorktree,
    CreatePaneInSession,
    CreateSession,
    CreateSessionWithExistingWorktree,
    CreateSessionWithWorktree,
    DetachSession,
    DevPanelCommitDiff,
    DevPanelCreateDirectory,
    DevPanelCreateFile,
    DevPanelDeleteFile,
    DevPanelGetFileInfo,
    DevPanelGitCommit,
    DevPanelGitDiscard,
    DevPanelGitFetch,
    DevPanelGitLog,
    DevPanelGitPull,
    DevPanelGitPush,
    DevPanelGitStage,
    DevPanelGitStageAll,
    DevPanelGitStatus,
    DevPanelGitUnstage,
    DevPanelGitUnstageAll,
    DevPanelListBranches,
    DevPanelListDir,
    DevPanelReadBinary,
    DevPanelReadFile,
    DevPanelSqliteExportCSV,
    DevPanelSqliteListTables,
    DevPanelSqliteQueryTable,
    DevPanelRenameFile,
    DevPanelSearchFiles,
    DevPanelStartWatcher,
    DevPanelStopWatcher,
    DevPanelWriteFile,
    DevPanelWorkingDiff,
    FocusPane,
    GetActiveSession,
    GetAllowedShells,
    GetClaudeEnvVarDescriptions,
    GetCurrentBranch,
    GetPaneEnv,
    GetPaneReplay,
    GetConfig,
    GetConfigAndFlushWarnings,
    GetInputHistory,
    GetMCPDetail as GetMCPDetailRaw,
    GetInputHistoryFilePath,
    GetSessionErrorLog,
    GetSessionLogFilePath,
    LoadSessionMemo,
    GetValidationRules as GetValidationRulesWails,
    LogFrontendEvent,
    GetSessionEnv,
    GetWebSocketURL,
    GetSingleTaskRunnerClearDelay,
    GetSingleTaskRunnerStatus,
    IsAgentTeamsAvailable,
    IsGitRepository,
    InstallTmuxShim,
    KillPane,
    KillSession,
    ListBranches,
    ListMCPServers as ListMCPServersRaw,
    ListSessions,
    ListWorktreesByRepo,
    PickSessionDirectory,
    PromoteWorktreeToBranch,
    QuickStartSession,
    RecoverIMEWindowFocus,
    RenamePane,
    RenameSession,
    ResizePane,
    SaveConfig,
    SaveSessionMemo,
    SendInput,
    SendSyncInput,
    SetActiveSession,
    SplitPane,
    ToggleViewerSidebarMode,
    SwapPanes,
    OpenDirectoryInExplorer,
    LoadOrchestratorTeams,
    LoadPromptPresets as LoadPromptPresetsRaw,
    SaveOrchestratorTeam,
    SavePromptPreset,
    DeleteOrchestratorTeam,
    DeletePromptPreset,
    ReorderPromptPresets,
    ReorderSingleTaskRunnerItems,
    RemoveSingleTaskRunnerItem,
    SendChatMessage,
    SendDiffReview,
    SetSingleTaskRunnerClearDelay,
    StartOrchestratorTeam,
    StartAutoStartCommand,
    StartSingleTaskRunner,
    StopSingleTaskRunner,
    UpdateSingleTaskRunnerItem,
    ListOrchestratorTasks,
    ListOrchestratorAgents,
    GetPaneProcessStatus,
    GetOrchestratorTaskDetail,
} from "../wailsjs/go/main/App";
import type {MCPSnapshot} from "./types/mcp";
import {normalizeMCPSnapshot, normalizeMCPSnapshots} from "./types/mcp";
import type {ValidationRules} from "./types/tmux";
import type {PromptPresetLoadResult} from "./components/viewer/views/prompt-presets/types";

async function ListMCPServers(sessionName: string): Promise<MCPSnapshot[]> {
    const result = await ListMCPServersRaw(sessionName);
    return normalizeMCPSnapshots(result);
}

async function GetMCPDetail(sessionName: string, mcpID: string): Promise<MCPSnapshot> {
    // Used for targeted refresh paths (per-MCP updates on backend events).
    const result = await GetMCPDetailRaw(sessionName, mcpID);
    const normalized = normalizeMCPSnapshot(result);
    if (!normalized) {
        throw new Error("GetMCPDetail returned an invalid MCP payload");
    }
    return normalized;
}

async function LoadPromptPresets(sessionName: string): Promise<PromptPresetLoadResult> {
    return await LoadPromptPresetsRaw(sessionName) as unknown as PromptPresetLoadResult;
}

export const api = {
    AddSingleTaskRunnerItem,
    ApplyLayoutPreset,
    GetAllowedShells,
    GetActiveSession,
    GetClaudeEnvVarDescriptions,
    GetConfig,
    GetConfigAndFlushWarnings,
    GetMCPDetail,
    // GetValidationRules のみ型キャストが必要（Wails 自動生成型が ValidationRules と異なるため）。
    GetValidationRules: () => GetValidationRulesWails() as Promise<ValidationRules>,
    GetSessionEnv,
    GetSingleTaskRunnerClearDelay,
    GetSingleTaskRunnerStatus,
    IsAgentTeamsAvailable,
    ListMCPServers,
    ListSessions,
    PickSessionDirectory,
    QuickStartSession,
    CreatePaneInSession,
    CreateSession,
    CreateSessionWithWorktree,
    CreateSessionWithExistingWorktree,
    CheckDirectoryConflict,
    CheckWorktreePathConflict,
    CheckWorktreeStatus,
    CommitAndPushWorktree,
    GetCurrentBranch,
    RecoverIMEWindowFocus,
    SetActiveSession,
    SplitPane,
    SendInput,
    SendSyncInput,
    ResizePane,
    FocusPane,
    GetPaneEnv,
    GetPaneReplay,
    KillPane,
    KillSession,
    DetachSession,
    RenamePane,
    RenameSession,
    SaveConfig,
    SaveSessionMemo,
    SwapPanes,
    ToggleViewerSidebarMode,
    BuildStatusLine,
    IsGitRepository,
    InstallTmuxShim,
    ListBranches,
    ListWorktreesByRepo,
    PromoteWorktreeToBranch,
    CleanupWorktree,
    GetWebSocketURL,
    DevPanelListDir,
    DevPanelReadBinary,
    DevPanelReadFile,
    DevPanelSqliteListTables,
    DevPanelSqliteQueryTable,
    DevPanelSqliteExportCSV,
    DevPanelGetFileInfo,
    DevPanelWriteFile,
    DevPanelCreateFile,
    DevPanelCreateDirectory,
    DevPanelRenameFile,
    DevPanelDeleteFile,
    DevPanelStartWatcher,
    DevPanelStopWatcher,
    DevPanelSearchFiles,
    DevPanelGitLog,
    DevPanelGitStatus,
    DevPanelCommitDiff,
    DevPanelGitCommit,
    DevPanelGitDiscard,
    DevPanelGitFetch,
    DevPanelGitPull,
    DevPanelGitPush,
    DevPanelGitStage,
    DevPanelGitStageAll,
    DevPanelGitUnstage,
    DevPanelGitUnstageAll,
    DevPanelWorkingDiff,
    DevPanelListBranches,
    GetInputHistory,
    GetInputHistoryFilePath,
    GetSessionErrorLog,
    GetSessionLogFilePath,
    LoadSessionMemo,
    LogFrontendEvent,
    OpenDirectoryInExplorer,
    LoadOrchestratorTeams,
    LoadPromptPresets,
    SaveOrchestratorTeam,
    SavePromptPreset,
    DeleteOrchestratorTeam,
    DeletePromptPreset,
    ReorderPromptPresets,
    ReorderSingleTaskRunnerItems,
    RemoveSingleTaskRunnerItem,
    SendChatMessage,
    SendDiffReview,
    SetSingleTaskRunnerClearDelay,
    StartOrchestratorTeam,
    StartAutoStartCommand,
    StartSingleTaskRunner,
    StopSingleTaskRunner,
    UpdateSingleTaskRunnerItem,
    ListOrchestratorTasks,
    ListOrchestratorAgents,
    GetPaneProcessStatus,
    GetOrchestratorTaskDetail,
};
