// English descriptions for Claude Code environment variables.
// Meanings are sourced from app_claude_env_descriptions.go in the myT-x backend.
export const claudeEnvVarDescriptionsEn: Record<string, string> = {
    "ANTHROPIC_API_KEY": "API key sent as the X-Api-Key header. Typically used for Claude SDK (run /login for interactive use).",
    "ANTHROPIC_AUTH_TOKEN": "Custom value for the Authorization header (Bearer is prepended to this value).",
    "ANTHROPIC_CUSTOM_HEADERS": "Custom headers to add to requests (Name: Value format, newline-separated for multiple headers).",
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": "Default Haiku model selection in model configuration.",
    "ANTHROPIC_DEFAULT_OPUS_MODEL": "Default Opus model selection in model configuration.",
    "ANTHROPIC_DEFAULT_SONNET_MODEL": "Default Sonnet model selection in model configuration.",
    "ANTHROPIC_FOUNDRY_API_KEY": "API key for Microsoft Foundry authentication (see Microsoft Foundry documentation).",
    "ANTHROPIC_FOUNDRY_BASE_URL": "Full base URL for a Foundry resource (for example: https://my-resource.services.ai.azure.com/anthropic). Use as an alternative to ANTHROPIC_FOUNDRY_RESOURCE.",
    "ANTHROPIC_FOUNDRY_RESOURCE": "Foundry resource name (for example: my-resource). Required when ANTHROPIC_FOUNDRY_BASE_URL is not set.",
    "ANTHROPIC_MODEL": "Name of the model configuration to use.",
    "ANTHROPIC_SMALL_FAST_MODEL": "[Deprecated] Name of a Haiku-class model for background tasks.",
    "ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION": "Override AWS region for the Haiku-class model when using Bedrock.",
    "AWS_BEARER_TOKEN_BEDROCK": "Bedrock API key used for authentication.",
    "BASH_DEFAULT_TIMEOUT_MS": "Default timeout in milliseconds for long-running bash commands.",
    "BASH_MAX_OUTPUT_LENGTH": "Maximum bash output length before middle truncation is applied.",
    "BASH_MAX_TIMEOUT_MS": "Maximum timeout in milliseconds allowed for long-running bash commands.",
    "CLAUDE_AUTOCOMPACT_PCT_OVERRIDE": "Context usage percentage (1-100) that triggers auto-compaction. Default is about 95. Lower values such as 50 compact earlier. Values above default are ignored. Applies to main chat and subagents.",
    "CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR": "Return to the original working directory after each bash command.",
    "CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD": "Set to 1 to load CLAUDE.md from directories specified via --add-dir (additional directory memory files are not loaded by default).",
    "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS": "Set to 1 to enable experimental agent teams. Disabled by default.",
    "CLAUDE_CODE_API_KEY_HELPER_TTL_MS": "Interval in milliseconds for refreshing credentials when using apiKeyHelper.",
    "CLAUDE_CODE_CLIENT_CERT": "Path to client certificate file for mTLS authentication.",
    "CLAUDE_CODE_CLIENT_KEY_PASSPHRASE": "Passphrase for encrypted CLAUDE_CODE_CLIENT_KEY (optional).",
    "CLAUDE_CODE_CLIENT_KEY": "Path to client private key file for mTLS authentication.",
    "CLAUDE_CODE_EFFORT_LEVEL": "Reasoning effort level for supported models. Allowed values: low, medium, high (default). Lower is faster and cheaper; higher gives deeper reasoning. Currently supported only on Opus 4.6.",
    "CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS": "Set to 1 to disable Anthropic API specific anthropic-beta headers. Useful when third-party provider gateways fail with beta headers.",
    "CLAUDE_CODE_DISABLE_AUTO_MEMORY": "Set to 1 to disable auto memory. Set to 0 to force enable during phased rollout. When disabled, auto memory files are not created or read.",
    "CLAUDE_CODE_DISABLE_BACKGROUND_TASKS": "Set to 1 to disable all background task features (bash or subagent run_in_background, automatic backgrounding, and Ctrl+B shortcut).",
    "CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY": "Set to 1 to disable the session quality survey \"How is Claude doing?\". Also automatically disabled with third-party providers or telemetry-off configurations.",
    "CLAUDE_CODE_EXIT_AFTER_STOP_DELAY": "Wait time in milliseconds before auto exit after the query loop becomes idle. Useful for SDK mode automation workflows.",
    "CLAUDE_CODE_PROXY_RESOLVES_HOSTS": "Set to true to allow the proxy to resolve DNS hosts on behalf of the caller. Opt-in for proxy environments.",
    "CLAUDE_CODE_TASK_LIST_ID": "ID used to share task lists across sessions. Multiple Claude Code instances can share the same task list with this ID.",
    "CLAUDE_CODE_TEAM_NAME": "Team name automatically assigned to agent team members.",
    "CLAUDE_CODE_TMPDIR": "Override directory used for internal temporary files. /claude/ is appended to this path (default: /tmp on Unix or macOS, os.tmpdir() on Windows).",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "Equivalent to setting DISABLE_AUTOUPDATER, DISABLE_BUG_COMMAND, DISABLE_ERROR_REPORTING, and DISABLE_TELEMETRY.",
    "CLAUDE_CODE_DISABLE_TERMINAL_TITLE": "Set to 1 to disable automatic terminal title updates based on conversation context.",
    "CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION": "Set to false to disable prompt suggestion text shown in the input after Claude responses.",
    "CLAUDE_CODE_ENABLE_TASKS": "Set to false to temporarily fall back to the previous TODO list instead of task tracking (default: true).",
    "CLAUDE_CODE_ENABLE_TELEMETRY": "Set to 1 to enable OpenTelemetry metric and log collection. Required before configuring OTel exporters.",
    "CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS": "Override default token limit for file reads. Useful when full content from large files is required.",
    "CLAUDE_CODE_HIDE_ACCOUNT_INFO": "Set to 1 to hide email address and organization name in Claude Code UI. Useful for streaming or recording.",
    "CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL": "Skip automatic installation of IDE extensions.",
    "CLAUDE_CODE_MAX_OUTPUT_TOKENS": "Maximum output tokens for most requests. Default: 32,000 (max: 64,000). Increasing this can reduce effective context window before auto-compaction.",
    "CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS": "Refresh interval in milliseconds for dynamic OpenTelemetry headers (default: 1,740,000 or 29 minutes).",
    "CLAUDE_CODE_PLAN_MODE_REQUIRED": "Automatically set to true for agent team members that require plan approval (read-only).",
    "CLAUDE_CODE_SHELL": "Override automatic shell detection. Useful when login shell and execution shell differ (for example bash vs zsh).",
    "CLAUDE_CODE_SHELL_PREFIX": "Command prefix that wraps every bash command (for example for logging or auditing). Example: setting /path/to/logger.sh runs /path/to/logger.sh <command>.",
    "CLAUDE_CODE_SKIP_BEDROCK_AUTH": "Skip AWS authentication for Bedrock (for example when using an LLM gateway).",
    "CLAUDE_CODE_SKIP_FOUNDRY_AUTH": "Skip Azure authentication for Microsoft Foundry (for example when using an LLM gateway).",
    "CLAUDE_CODE_SKIP_VERTEX_AUTH": "Skip Google authentication for Vertex (for example when using an LLM gateway).",
    "CLAUDE_CODE_SUBAGENT_MODEL": "Model configuration used by subagents.",
    "CLAUDE_CODE_USE_BEDROCK": "Use Bedrock.",
    "CLAUDE_CODE_USE_FOUNDRY": "Use Microsoft Foundry.",
    "CLAUDE_CODE_USE_VERTEX": "Use Vertex.",
    "CLAUDE_CONFIG_DIR": "Customize where Claude Code stores configuration and data files.",
    "DISABLE_AUTOUPDATER": "Set to 1 to disable automatic updates.",
    "DISABLE_BUG_COMMAND": "Set to 1 to disable the /bug command.",
    "DISABLE_COST_WARNINGS": "Set to 1 to disable cost warning messages.",
    "DISABLE_ERROR_REPORTING": "Set to 1 to opt out of Sentry error reporting.",
    "DISABLE_INSTALLATION_CHECKS": "Set to 1 to disable installation warnings. Use only when installation locations are manually managed, because standard installation issues may be hidden.",
    "DISABLE_NON_ESSENTIAL_MODEL_CALLS": "Set to 1 to disable model calls on non-essential paths such as flavor text.",
    "DISABLE_PROMPT_CACHING": "Set to 1 to disable prompt caching for all models (overrides per-model settings).",
    "DISABLE_PROMPT_CACHING_HAIKU": "Set to 1 to disable prompt caching for Haiku models.",
    "DISABLE_PROMPT_CACHING_OPUS": "Set to 1 to disable prompt caching for Opus models.",
    "DISABLE_PROMPT_CACHING_SONNET": "Set to 1 to disable prompt caching for Sonnet models.",
    "DISABLE_TELEMETRY": "Set to 1 to opt out of Statsig telemetry (Statsig events do not include user data such as code, file paths, or commands).",
    "ENABLE_TOOL_SEARCH": "Controls MCP tool search. Values: auto (default, enabled for 10%), auto:N (custom threshold), true (always on), false (disabled).",
    "FORCE_AUTOUPDATE_PLUGINS": "Set to true to force plugin auto-updates even when the main auto-updater is disabled.",
    "HTTP_PROXY": "Specify the HTTP proxy server for network connections.",
    "HTTPS_PROXY": "Specify the HTTPS proxy server for network connections.",
    "IS_DEMO": "Set to true to enable demo mode (hide personal information in UI, skip onboarding, and hide internal commands). Useful for streaming or recording.",
    "MAX_MCP_OUTPUT_TOKENS": "Maximum tokens for MCP tool responses. A warning is shown when output exceeds 10,000 tokens (default: 25,000).",
    "MAX_THINKING_TOKENS": "Override token budget for extended thinking. Default is maximum (31,999). Set to 0 to disable. On Opus 4.6, thinking depth is controlled by effort level, so non-zero values are ignored.",
    "MCP_CLIENT_SECRET": "OAuth client secret for MCP servers that require preconfiguration. Used to avoid --client-secret prompts.",
    "MCP_OAUTH_CALLBACK_PORT": "Fixed port for OAuth redirect callbacks (alternative to --callback-port).",
    "MCP_TIMEOUT": "Timeout in milliseconds for MCP server startup.",
    "MCP_TOOL_TIMEOUT": "Timeout in milliseconds for MCP tool execution.",
    "NO_PROXY": "List of domains and IP addresses that should bypass the proxy and be requested directly.",
    "SLASH_COMMAND_TOOL_CHAR_BUDGET": "Override character budget for metadata shown in the Skill tool. Default is 2% of context (fallback 16,000 chars). Legacy name.",
    "USE_BUILTIN_RIPGREP": "Set to 0 to use system-installed rg instead of built-in rg.",
    "VERTEX_REGION_CLAUDE_3_5_HAIKU": "Override region for Claude 3.5 Haiku on Vertex AI.",
    "VERTEX_REGION_CLAUDE_3_7_SONNET": "Override region for Claude 3.7 Sonnet on Vertex AI.",
    "VERTEX_REGION_CLAUDE_4_0_OPUS": "Override region for Claude 4.0 Opus on Vertex AI.",
    "VERTEX_REGION_CLAUDE_4_0_SONNET": "Override region for Claude 4.0 Sonnet on Vertex AI.",
    "VERTEX_REGION_CLAUDE_4_1_OPUS": "Override region for Claude 4.1 Opus on Vertex AI",
};

export default claudeEnvVarDescriptionsEn;
