package main

// claudeEnvVarDescriptions holds Claude Code environment variable names and their
// Japanese descriptions. Used by the frontend settings UI to provide autocomplete
// suggestions and explanations when configuring Claude Code environment variables.
var claudeEnvVarDescriptions = map[string]string{
	"ANTHROPIC_API_KEY":                            "X-Api-Key ヘッダーとして送信されるAPIキー。通常はClaude SDK用に使用されます（対話的な使用には /login を実行してください）。",
	"ANTHROPIC_AUTH_TOKEN":                         "Authorization ヘッダーのカスタム値（ここで設定した値の前に Bearer が付加されます）。",
	"ANTHROPIC_CUSTOM_HEADERS":                     "リクエストに追加するカスタムヘッダー（Name: Value 形式、複数の場合は改行区切り）。",
	"ANTHROPIC_DEFAULT_HAIKU_MODEL":                "モデル設定を参照（Haikuモデルのデフォルト指定）。",
	"ANTHROPIC_DEFAULT_OPUS_MODEL":                 "モデル設定を参照（Opusモデルのデフォルト指定）。",
	"ANTHROPIC_DEFAULT_SONNET_MODEL":               "モデル設定を参照（Sonnetモデルのデフォルト指定）。",
	"ANTHROPIC_FOUNDRY_API_KEY":                    "Microsoft Foundry認証用のAPIキー（Microsoft Foundryのドキュメントを参照）。",
	"ANTHROPIC_FOUNDRY_BASE_URL":                   "Foundryリソースの完全なベースURL（例：https://my-resource.services.ai.azure.com/anthropic）。ANTHROPIC_FOUNDRY_RESOURCE の代替として使用。",
	"ANTHROPIC_FOUNDRY_RESOURCE":                   "Foundryリソース名（例：my-resource）。ANTHROPIC_FOUNDRY_BASE_URL が未設定の場合に必須。",
	"ANTHROPIC_MODEL":                              "使用するモデル設定の名前（Model Configurationを参照）。",
	"ANTHROPIC_SMALL_FAST_MODEL":                   "[非推奨] バックグラウンドタスク用のHaikuクラスモデルの名前。",
	"ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION":        "Bedrock使用時のHaikuクラスモデル用のAWSリージョンを上書き設定。",
	"AWS_BEARER_TOKEN_BEDROCK":                     "認証用のBedrock APIキー（Bedrock API keysを参照）。",
	"BASH_DEFAULT_TIMEOUT_MS":                      "長時間実行されるbashコマンドのデフォルトタイムアウト時間（ミリ秒）。",
	"BASH_MAX_OUTPUT_LENGTH":                       "bash出力が中間切り捨て（middle-truncated）されるまでの最大文字数。",
	"BASH_MAX_TIMEOUT_MS":                          "モデルが長時間実行されるbashコマンドに対して設定できる最大タイムアウト時間（ミリ秒）。",
	"CLAUDE_AUTOCOMPACT_PCT_OVERRIDE":              "自動圧縮（auto-compaction）がトリガーされるコンテキスト容量の割合（1-100）。デフォルトは約95%。50 のような低い値を設定すると早めに圧縮されます。デフォルト以上の値は無効。メイン会話とサブエージェント両方に適用。",
	"CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR":     "各Bashコマンド実行後に、元の作業ディレクトリに戻る設定。",
	"CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD": "1 に設定すると、--add-dir で指定したディレクトリから CLAUDE.md ファイルを読み込みます（デフォルトでは追加ディレクトリのメモリファイルは読み込まれません）。",
	"CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS":         "1 に設定すると、エージェントチーム（agent teams）機能を有効化。これは実験的な機能であり、デフォルトでは無効です。",
	"CLAUDE_CODE_API_KEY_HELPER_TTL_MS":            "apiKeyHelper 使用時に認証情報をリフレッシュする間隔（ミリ秒）。",
	"CLAUDE_CODE_CLIENT_CERT":                      "mTLS認証用のクライアント証明書ファイルへのパス。",
	"CLAUDE_CODE_CLIENT_KEY_PASSPHRASE":            "暗号化された CLAUDE_CODE_CLIENT_KEY のパスフレーズ（オプション）。",
	"CLAUDE_CODE_CLIENT_KEY":                       "mTLS認証用のクライアント秘密鍵ファイルへのパス。",
	"CLAUDE_CODE_EFFORT_LEVEL":                     "サポートされているモデルの思考レベルを設定。値：low, medium, high（デフォルト）。低いほど速く安価、高いほど深い推論を行います。現在は Opus 4.6 でのみサポート。",
	"CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS":       "1 に設定すると、Anthropic API固有の anthropic-beta ヘッダーを無効化。サードパーティプロバイダーとのLLMゲートウェイ使用時にエラーが出る場合などに使用。",
	"CLAUDE_CODE_DISABLE_AUTO_MEMORY":              "1 で自動メモリ（auto memory）を無効化。0 で段階的ロールアウト中に強制有効化。無効時は自動メモリファイルの作成・読み込みを行いません。",
	"CLAUDE_CODE_DISABLE_BACKGROUND_TASKS":         "1 で全てのバックグラウンドタスク機能（Bashやサブエージェントツールの run_in_background、自動バックグラウンド化、Ctrl+Bショートカット）を無効化。",
	"CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY":          "1 で「How is Claude doing?」というセッション品質調査を無効化。サードパーティプロバイダー使用時やテレメトリ無効時も自動的に無効になります。",
	"CLAUDE_CODE_EXIT_AFTER_STOP_DELAY":            "クエリループがアイドル状態になってから自動終了するまでの待機時間（ミリ秒）。SDKモードを使用した自動化ワークフロー等に有用。",
	"CLAUDE_CODE_PROXY_RESOLVES_HOSTS":             "true に設定すると、呼び出し元の代わりにプロキシがDNS解決を行うことを許可。プロキシ環境向けのオプトイン設定。",
	"CLAUDE_CODE_TASK_LIST_ID":                     "セッション間でタスクリストを共有するためのID。複数のClaude Codeインスタンスで同じIDを設定し、タスクリストを共有します。",
	"CLAUDE_CODE_TEAM_NAME":                        "エージェントチームのメンバーに自動的に設定される、所属チームの名前。",
	"CLAUDE_CODE_TMPDIR":                           "内部一時ファイルに使用されるディレクトリを上書き。このパスに /claude/ が追加されます（デフォルト: Unix/macOSは /tmp、Windowsは os.tmpdir()）。",
	"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC":     "DISABLE_AUTOUPDATER、DISABLE_BUG_COMMAND、DISABLE_ERROR_REPORTING、DISABLE_TELEMETRY を全て設定するのと同等。",
	"CLAUDE_CODE_DISABLE_TERMINAL_TITLE":           "1 に設定すると、会話コンテキストに基づく端末タイトルの自動更新を無効化。",
	"CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION":         "false でプロンプト提案（Claude応答後の入力欄に表示されるグレーの予測テキスト）を無効化。",
	"CLAUDE_CODE_ENABLE_TASKS":                     "false でタスク追跡システムの代わりに以前のTODOリストへ一時的に戻します（デフォルト: true）。",
	"CLAUDE_CODE_ENABLE_TELEMETRY":                 "1 でメトリクスとログのOpenTelemetryデータ収集を有効化。OTelエクスポーター設定前に必須。",
	"CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS":      "ファイル読み込みのデフォルトトークン制限を上書き。大きなファイルを完全に読み込む必要がある場合に有用。",
	"CLAUDE_CODE_HIDE_ACCOUNT_INFO":                "1 でClaude Code UI上のメールアドレスと組織名を非表示にする。ストリーミングや録画時に有用。",
	"CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL":            "IDE拡張機能の自動インストールをスキップする設定。",
	"CLAUDE_CODE_MAX_OUTPUT_TOKENS":                "ほとんどのリクエストに対する最大出力トークン数。デフォルト: 32,000（最大: 64,000）。値を増やすと、自動圧縮までの有効コンテキストウィンドウが減少します。",
	"CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS":  "動的OpenTelemetryヘッダーのリフレッシュ間隔（ミリ秒）（デフォルト: 1,740,000 / 29分）。",
	"CLAUDE_CODE_PLAN_MODE_REQUIRED":               "計画承認が必要なエージェントチームメンバーに対して自動的に true に設定される（読み取り専用）。",
	"CLAUDE_CODE_SHELL":                            "自動シェル検出を上書き。ログインシェルと作業用シェルが異なる場合（例：bash vs zsh）に有用。",
	"CLAUDE_CODE_SHELL_PREFIX":                     "すべてのbashコマンドをラップするコマンドプレフィックス（例：ログ記録や監査用）。例：/path/to/logger.sh を設定すると /path/to/logger.sh <command> が実行されます。",
	"CLAUDE_CODE_SKIP_BEDROCK_AUTH":                "BedrockのAWS認証をスキップ（LLMゲートウェイ使用時など）。",
	"CLAUDE_CODE_SKIP_FOUNDRY_AUTH":                "Microsoft FoundryのAzure認証をスキップ（LLMゲートウェイ使用時など）。",
	"CLAUDE_CODE_SKIP_VERTEX_AUTH":                 "VertexのGoogle認証をスキップ（LLMゲートウェイ使用時など）。",
	"CLAUDE_CODE_SUBAGENT_MODEL":                   "サブエージェント用モデル設定を参照。",
	"CLAUDE_CODE_USE_BEDROCK":                      "Bedrockを使用する設定。",
	"CLAUDE_CODE_USE_FOUNDRY":                      "Microsoft Foundryを使用する設定。",
	"CLAUDE_CODE_USE_VERTEX":                       "Vertexを使用する設定。",
	"CLAUDE_CONFIG_DIR":                            "Claude Codeが設定ファイルやデータファイルを保存する場所をカスタマイズ。",
	"DISABLE_AUTOUPDATER":                          "1 で自動更新を無効化。",
	"DISABLE_BUG_COMMAND":                          "1 で /bug コマンドを無効化。",
	"DISABLE_COST_WARNINGS":                        "1 でコスト警告メッセージを無効化。",
	"DISABLE_ERROR_REPORTING":                      "1 でSentryへのエラー報告をオプトアウト。",
	"DISABLE_INSTALLATION_CHECKS":                  "1 でインストール警告を無効化。インストール場所を手動管理している場合のみ使用（標準インストールの問題を隠蔽する可能性があるため）。",
	"DISABLE_NON_ESSENTIAL_MODEL_CALLS":            "1 でフレーバーテキストなどの、重要でないパスのモデル呼び出しを無効化。",
	"DISABLE_PROMPT_CACHING":                       "1 で全モデルのプロンプトキャッシュを無効化（モデルごとの設定より優先）。",
	"DISABLE_PROMPT_CACHING_HAIKU":                 "1 でHaikuモデルのプロンプトキャッシュを無効化。",
	"DISABLE_PROMPT_CACHING_OPUS":                  "1 でOpusモデルのプロンプトキャッシュを無効化。",
	"DISABLE_PROMPT_CACHING_SONNET":                "1 でSonnetモデルのプロンプトキャッシュを無効化。",
	"DISABLE_TELEMETRY":                            "1 でStatsigテレメトリをオプトアウト（Statsigイベントにはコード、ファイルパス、コマンド等のユーザーデータは含まれません）。",
	"ENABLE_TOOL_SEARCH":                           "MCPツール検索の制御。値：auto（デフォルト、10%で有効）、auto:N（カスタム閾値）、true（常時オン）、false（無効）。",
	"FORCE_AUTOUPDATE_PLUGINS":                     "true で、メインの自動更新が無効でもプラグインの自動更新を強制する。",
	"HTTP_PROXY":                                   "ネットワーク接続用のHTTPプロキシサーバーを指定。",
	"HTTPS_PROXY":                                  "ネットワーク接続用のHTTPSプロキシサーバーを指定。",
	"IS_DEMO":                                      "true でデモモードを有効化（UIから個人情報を隠し、オンボーディングをスキップ、内部コマンドを隠す）。ストリーミングや録画用。",
	"MAX_MCP_OUTPUT_TOKENS":                        "MCPツール応答の最大トークン数。出力が10,000トークンを超えると警告が表示されます（デフォルト: 25,000）。",
	"MAX_THINKING_TOKENS":                          "拡張思考（extended thinking）のトークン予算を上書き。デフォルトは最大（31,999）。0 で無効化。Opus 4.6では思考深度は effort level で制御されるため、0（無効化）以外は無視されます。",
	"MCP_CLIENT_SECRET":                            "事前設定が必要なMCPサーバー用のOAuthクライアントシークレット。--client-secret プロンプトを回避するために使用。",
	"MCP_OAUTH_CALLBACK_PORT":                      "OAuthリダイレクトコールバック用の固定ポートを指定（--callback-port の代替）。",
	"MCP_TIMEOUT":                                  "MCPサーバー起動のタイムアウト時間（ミリ秒）。",
	"MCP_TOOL_TIMEOUT":                             "MCPツール実行のタイムアウト時間（ミリ秒）。",
	"NO_PROXY":                                     "プロキシを経由せず直接リクエストを発行するドメインとIPのリスト。",
	"SLASH_COMMAND_TOOL_CHAR_BUDGET":               "Skill toolに表示されるメタデータの文字数予算を上書き。デフォルトはコンテキストの2%（フォールバック16,000文字）。レガシー名。",
	"USE_BUILTIN_RIPGREP":                          "0 に設定すると、内蔵 rg の代わりにシステムにインストールされた rg を使用。",
	"VERTEX_REGION_CLAUDE_3_5_HAIKU":               "Vertex AI使用時の Claude 3.5 Haiku のリージョン上書き。",
	"VERTEX_REGION_CLAUDE_3_7_SONNET":              "Vertex AI使用時の Claude 3.7 Sonnet のリージョン上書き。",
	"VERTEX_REGION_CLAUDE_4_0_OPUS":                "Vertex AI使用時の Claude 4.0 Opus のリージョン上書き。",
	"VERTEX_REGION_CLAUDE_4_0_SONNET":              "Vertex AI使用時の Claude 4.0 Sonnet のリージョン上書き。",
	"VERTEX_REGION_CLAUDE_4_1_OPUS":                "Vertex AI使用時の Claude 4.1 Opus のリージョン上書き。",
}
